[build]
  command = "node debug-preprocess.js && node generate-dashboard-data.js && CI=false TSC_COMPILE_ON_ERROR=true DISABLE_ESLINT_PLUGIN=true GENERATE_SOURCEMAP=false react-scripts build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Handle React Router's client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 